// Brand components. The artwork itself lives in public/brand (generated by
// scripts/brand.mjs — edit that, not the SVGs); these just place it.

export const TAGLINE = "One buyer. Eight arms.";

/** The octagon-coin mark on its own. */
export function LogoMark({ size = 28, className = "" }: { size?: number; className?: string }) {
  return <img src="/brand/logo-mark.svg" width={size} height={size} alt="" aria-hidden className={`inline-block shrink-0 ${className}`} draggable={false} />;
}

/** Mark + wordmark, sized by the text. */
export function Logo({ className = "", markSize = 28 }: { className?: string; markSize?: number }) {
  return (
    <span className={`inline-flex items-center gap-2 font-black tracking-tight ${className}`}>
      <LogoMark size={markSize} />
      <span>
        <span className="text-slate-100">MONOPSONY</span>
      </span>
    </span>
  );
}

/** Mono the octopus. `pose` "coin" holds the logo coin up; "plain" keeps all eight arms down. */
export function Mascot({ size = 120, pose = "coin", className = "" }: { size?: number; pose?: "coin" | "plain"; className?: string }) {
  return (
    <img
      src={pose === "coin" ? "/brand/mono.svg" : "/brand/mono-plain.svg"}
      width={size}
      height={size}
      alt="Mono, the Monopsony octopus"
      className={`select-none ${className}`}
      draggable={false}
    />
  );
}
