// Code generated by tygo. DO NOT EDIT.
// GENERATED by tygo from server/internal/game — do not edit.
/* eslint-disable */

//////////
// source: config.go
/*
Package game is the pure, deterministic Monopoly-rules engine.

It has no I/O and no goroutines: callers feed Commands into Apply and get
back Events. Everything the UI, the bots, and the persistence layer need is
derived from the State and the Event stream.
*/

/**
 * SpaceType classifies the 40 board spaces.
 */
export type SpaceType = string;
export const SpaceGo: SpaceType = "go";
export const SpaceStreet: SpaceType = "street";
export const SpaceRailroad: SpaceType = "railroad";
export const SpaceUtility: SpaceType = "utility";
export const SpaceChance: SpaceType = "chance";
export const SpaceCommunityChest: SpaceType = "community_chest";
export const SpaceTax: SpaceType = "tax";
export const SpaceJail: SpaceType = "jail";
export const SpaceFreeParking: SpaceType = "free_parking";
export const SpaceGoToJail: SpaceType = "go_to_jail";
/**
 * Group identifiers for non-street ownable spaces.
 */
export const GroupRailroad = "railroad";
/**
 * Group identifiers for non-street ownable spaces.
 */
export const GroupUtility = "utility";
/**
 * SpaceDef is the static definition of a board space (admin-editable).
 */
export interface SpaceDef {
  index: number /* int */;
  name: string;
  type: SpaceType;
  group?: string; // colour group id, "railroad" or "utility"
  color?: string; // hex, for the UI only
  price?: number /* int */;
  rent: number /* int */[]; // streets: base, 1..4 houses, hotel
  houseCost?: number /* int */;
  taxAmount?: number /* int */;
}
/**
 * CardEffect is the kind of thing a Chance / Community Chest card does.
 */
export type CardEffect = string;
export const CardMoney: CardEffect = "money"; // Amount from (negative) or to (positive) the player
export const CardMoveTo: CardEffect = "move_to"; // Target space, collecting Go salary if passed
export const CardMoveBack: CardEffect = "move_back"; // Steps backwards
export const CardMoveToNearest: CardEffect = "move_to_nearest"; // Group railroad/utility; special rent
export const CardGoToJail: CardEffect = "go_to_jail";
export const CardGetOutOfJail: CardEffect = "get_out_of_jail"; // kept by player until used
export const CardRepairs: CardEffect = "repairs"; // PerHouse / PerHotel to the bank
export const CardCollectFromEach: CardEffect = "collect_from_each"; // Amount from every other player
export const CardPayEach: CardEffect = "pay_each"; // Amount to every other player
/**
 * CardDef is a single Chance / Community Chest card (admin-editable).
 */
export interface CardDef {
  id: string;
  text: string;
  effect: CardEffect;
  amount?: number /* int */;
  target?: number /* int */;
  steps?: number /* int */;
  group?: string;
  perHouse?: number /* int */;
  perHotel?: number /* int */;
}
/**
 * Rules are the numeric / boolean knobs. The classic values are the defaults;
 * house-rule toggles are gated by the paid tier at the lobby level, not here.
 */
export interface Rules {
  startCash: number /* int */;
  goSalary: number /* int */;
  jailFine: number /* int */;
  maxJailTurns: number /* int */; // failed rolls before the fine is forced
  maxDoubles: number /* int */; // consecutive doubles that send you to jail
  houseSupply: number /* int */;
  hotelSupply: number /* int */;
  mortgageInterestPct: number /* int */;
  buildingSellPct: number /* int */;
  auctionsEnabled: boolean;
  /**
   * House rules (off by default):
   */
  freeParkingJackpot: boolean;
  doubleSalaryOnGoLanding: boolean;
  noRentInJail: boolean;
  turnLimit: number /* int */; // 0 = play to last player standing
}
/**
 * Config is a complete, immutable game definition. Games pin a config for life.
 */
export interface Config {
  id: string;
  name: string;
  currency: string;
  spaces: SpaceDef[];
  chance: CardDef[];
  communityChest: CardDef[];
  rules: Rules;
}
/**
 * BoardSize is fixed by the rules engine; configs may rename/re-price but not resize.
 */
export const BoardSize = 40;

//////////
// source: events.go

/**
 * Event is something that happened. Events are the unit of persistence
 * (append-only log), of broadcast (every client sees the same stream) and of
 * animation (the 3D client plays them in order).
 */
export type Event = any;
export interface GameStarted {
  configId: string;
  players: Player[];
}
export interface DiceRolled {
  playerId: string;
  dice: number /* int */[];
  doubles: boolean;
  doublesCount: number /* int */;
  inJail: boolean;
}
/**
 * TokenMoved is emitted for every displacement. Forward moves pass Go
 * when To < From; card teleports set ViaCard.
 */
export interface TokenMoved {
  playerId: string;
  from: number /* int */;
  to: number /* int */;
  passedGo: boolean;
  viaCard: boolean;
  backward: boolean;
}
/**
 * CashChanged accompanies every cash movement (bank or player side).
 */
export interface CashChanged {
  playerId: string;
  delta: number /* int */;
  balance: number /* int */;
  reason: string;
}
export interface SalaryCollected {
  playerId: string;
  amount: number /* int */;
}
export interface PurchaseOffered {
  playerId: string;
  space: number /* int */;
  price: number /* int */;
}
export interface PropertyBought {
  playerId: string;
  space: number /* int */;
  price: number /* int */;
}
export interface PurchaseDeclined {
  playerId: string;
  space: number /* int */;
}
export interface AuctionStarted {
  space: number /* int */;
  bidders: string[];
  turnId: string;
}
export interface BidPlaced {
  playerId: string;
  amount: number /* int */;
  nextTurnId: string;
}
export interface BidPassed {
  playerId: string;
  nextTurnId: string;
}
export interface AuctionEnded {
  space: number /* int */;
  winnerId?: string; // empty = unsold
  amount: number /* int */;
}
export interface RentPaid {
  payerId: string;
  ownerId: string;
  space: number /* int */;
  amount: number /* int */;
}
export interface TaxPaid {
  playerId: string;
  space: number /* int */;
  amount: number /* int */;
}
export interface CardDrawn {
  playerId: string;
  deck: string; // "chance" | "community_chest"
  cardId: string;
  text: string;
}
export interface CardKept {
  playerId: string;
  cardId: string;
}
export interface UtilityRoll {
  playerId: string;
  dice: number /* int */[];
}
export interface SentToJail {
  playerId: string;
  reason: string; // "space" | "card" | "doubles"
}
export interface JailFinePaid {
  playerId: string;
  amount: number /* int */;
  forced: boolean;
}
export interface JailCardUsed {
  playerId: string;
  cardId: string;
}
export interface LeftJail {
  playerId: string;
  how: string; // "fine" | "card" | "doubles"
}
export interface JailTurnServed {
  playerId: string;
  turns: number /* int */;
}
export interface HouseBuilt {
  playerId: string;
  space: number /* int */;
  houses: number /* int */; // resulting count (5 = hotel)
  cost: number /* int */;
}
export interface HouseSold {
  playerId: string;
  space: number /* int */;
  houses: number /* int */; // resulting count
  refund: number /* int */;
}
export interface Mortgaged {
  playerId: string;
  space: number /* int */;
  amount: number /* int */;
}
export interface Unmortgaged {
  playerId: string;
  space: number /* int */;
  amount: number /* int */;
}
export interface TradeProposed {
  trade: Trade;
}
export interface TradeAccepted {
  tradeId: string;
}
export interface TradeRejected {
  tradeId: string;
  byId: string;
}
export interface PropertyTransferred {
  space: number /* int */;
  fromId?: string;
  toId?: string;
  reason: string; // "trade" | "bankruptcy"
}
export interface DebtIncurred {
  debt: Debt;
}
export interface DebtSettled {
  debt: Debt;
}
export interface PlayerBankrupt {
  playerId: string;
  creditorId?: string;
  reason?: string; // "insolvent" | "surrender"
}
export interface FreeParkingCollected {
  playerId: string;
  amount: number /* int */;
}
export interface PhaseChanged {
  phase: Phase;
}
export interface TurnChanged {
  playerId: string;
  number: number /* int */;
}
export interface GameEnded {
  winnerId: string;
  reason: string; // "last_standing" | "turn_limit"
}
/**
 * EventEnvelope is the log/wire form of an event.
 */
export interface EventEnvelope {
  seq: number /* int */;
  type: string;
  payload: unknown;
}

//////////
// source: harbourside.go


//////////
// source: legal.go

/**
 * Action is one thing a player may do right now. The UI renders these as
 * buttons; bots pick from them. Space/MinBid/TradeID are filled where relevant.
 */
export interface Action {
  type: string;
  space?: number /* int */;
  minBid?: number /* int */;
  tradeId?: string;
}

//////////
// source: state.go

/**
 * Phase is where the game is waiting for input.
 */
export type Phase = string;
export const PhasePreRoll: Phase = "pre_roll"; // current player may roll, trade, build, mortgage, or resolve jail
export const PhaseResolving: Phase = "resolving"; // current player must decide on an unowned property
export const PhaseAuction: Phase = "auction"; // bidding in progress
export const PhasePostRoll: Phase = "post_roll"; // current player may trade/build/mortgage, then end turn
export const PhaseRaisingFunds: Phase = "raising_funds"; // a debtor must sell/mortgage or declare bankruptcy
export const PhaseGameOver: Phase = "game_over";
/**
 * Player is a seat at the table.
 */
export interface Player {
  id: string;
  name: string;
  isBot: boolean;
  cash: number /* int */;
  position: number /* int */;
  inJail: boolean;
  jailTurns: number /* int */; // failed roll attempts while in jail
  jailCards: string[]; // card IDs held
  bankrupt: boolean;
  doublesCount: number /* int */; // consecutive doubles this turn
}
/**
 * SpaceState is the mutable part of a board space.
 */
export interface SpaceState {
  ownerId?: string;
  houses: number /* int */; // 0-4 houses, 5 = hotel
  mortgaged: boolean;
}
/**
 * Turn tracks the current player's turn progress.
 */
export interface Turn {
  number: number /* int */; // increments each time play passes to a new player
  playerIdx: number /* int */;
  phase: Phase;
  lastRoll: number /* int */[];
  rolled: boolean; // has rolled at least once this turn
  canRollAgain: boolean; // rolled doubles and wasn't jailed
  specialRent: boolean; // landed via a "nearest railroad/utility" card
  pendingJailMove: boolean; // forced jail fine went to debt; move after it clears
}
/**
 * Auction is an in-progress auction for one space. Bidding rotates among
 * Active players; a player either outbids or passes (dropping out). The
 * auction ends when one active player remains with a bid, or when every
 * player has passed with no bid.
 */
export interface Auction {
  spaceIndex: number /* int */;
  highBid: number /* int */;
  highBidderId?: string;
  active: string[]; // player IDs still in, in bid order
  turnId: string; // whose bid it is
  resumePhase: Phase;
}
/**
 * TradeSide is what one party gives.
 */
export interface TradeSide {
  cash: number /* int */;
  properties: number /* int */[];
  jailCards: number /* int */;
}
/**
 * Trade is a pending proposal.
 */
export interface Trade {
  id: string;
  fromId: string;
  toId: string;
  give: TradeSide; // what From gives
  receive: TradeSide; // what From receives
  resumePhase: Phase;
}
/**
 * Debt is an obligation that could not be paid from cash.
 */
export interface Debt {
  debtorId: string;
  creditorId?: string; // "" = the bank
  amount: number /* int */;
  reason: string;
}
/**
 * Decks holds the shuffled draw order for each deck. Drawn cards go to the
 * bottom; a Get Out of Jail Free card is removed until the holder uses it.
 */
export interface Decks {
  chance: string[];
  communityChest: string[];
}
/**
 * Bank tracks limited resources.
 */
export interface Bank {
  houses: number /* int */;
  hotels: number /* int */;
  freeParkingPool: number /* int */; // house rule only
}
/**
 * State is the complete game state. It is JSON-serialisable and is the
 * snapshot sent to clients (with per-viewer redaction handled elsewhere).
 */
export interface State {
  configId: string;
  players: Player[];
  spaces: SpaceState[];
  turn: Turn;
  bank: Bank;
  decks: Decks;
  auction?: Auction;
  trade?: Trade;
  debts?: Debt[];
  pendingAuctions?: number /* int */[]; // spaces to auction after a bank bankruptcy
  resumePhase?: Phase; // where to return after debts clear
  winnerId?: string;
  seq: number /* int */; // number of events emitted so far
  nextTradeId: number /* int */;
}
