// Code generated by tygo. DO NOT EDIT.
// GENERATED by tygo from server/internal/protocol — do not edit.
/* eslint-disable */
import type { Rules, Config, State, Action } from "./game";

//////////
// source: protocol.go
/*
Package protocol defines every message exchanged over the WebSocket. It is
the single source of truth for the TypeScript client types (generated with
tygo into packages/protocol).
*/

/**
 * Envelope wraps every frame in both directions.
 */
export interface Envelope {
  t: string;
  ref?: string; // client-chosen id echoed on Ack/Error
  p?: unknown;
}
/**
 * Client message types.
 */
export const CJoinGame = "JoinGame"; // subscribe to a room (lobby or in-progress)
/**
 * Client message types.
 */
export const CLeaveGame = "LeaveGame"; // unsubscribe
/**
 * Client message types.
 */
export const CCommand = "Command"; // a game.Command
/**
 * Client message types.
 */
export const CReady = "Ready"; // lobby: toggle ready
/**
 * Client message types.
 */
export const CChat = "Chat";
/**
 * Client message types.
 */
export const CPing = "Ping";
export interface JoinGame {
  gameId: string;
  lastSeq: number /* int */; // events after this seq are replayed
}
export interface LeaveGame {
  gameId: string;
}
export interface Command {
  gameId: string;
  type: string;
  payload?: unknown;
}
export interface Chat {
  gameId: string;
  text: string;
}
/**
 * Server message types.
 */
export const SWelcome = "Welcome";
/**
 * Server message types.
 */
export const SSnapshot = "Snapshot";
/**
 * Server message types.
 */
export const SEvent = "Event";
/**
 * Server message types.
 */
export const SUpdate = "Update";
/**
 * Server message types.
 */
export const SLobby = "Lobby";
/**
 * Server message types.
 */
export const SChat = "Chat";
/**
 * Server message types.
 */
export const SKicked = "Kicked"; // to the removed user only: they no longer hold a seat
/**
 * Server message types.
 */
export const SAck = "Ack";
/**
 * Server message types.
 */
export const SError = "Error";
/**
 * Server message types.
 */
export const SPong = "Pong";
export interface Welcome {
  userId: string;
  name: string;
}
/**
 * SeatInfo is what everyone can see about a seat.
 */
export interface SeatInfo {
  playerId: string;
  name: string;
  isBot: boolean;
  connected: boolean;
  ready: boolean;
  host: boolean;
  loadout?: { [key: string]: string}; // cosmetic slot -> item id
}
/**
 * Lobby is the pre-game room view.
 */
export interface Lobby {
  gameId: string;
  status: string; // "lobby" | "in_progress" | "finished"
  name: string;
  visibility: string; // "public" | "private"
  inviteCode?: string;
  maxPlayers: number /* int */;
  configId: string;
  rules: Rules;
  seats: SeatInfo[];
  turnSeconds: number /* int */;
  /**
   * Node hosts the game (cluster deployments; empty on a single server).
   */
  node?: string;
}
/**
 * Snapshot is the full game view sent on join/reconnect.
 */
export interface Snapshot {
  gameId: string;
  config?: Config;
  state?: State;
  seats: SeatInfo[];
  legal: Action[];
  waitingOn: string[];
  deadline?: number /* int64 */; // unix ms when the current wait times out
}
/**
 * Event is one game event with its sequence number.
 */
export interface Event {
  gameId: string;
  seq: number /* int */;
  type: string;
  payload: unknown;
}
/**
 * Update is sent to each subscriber after every state change: the new
 * authoritative state plus that player's legal actions. Events describe *how*
 * the state changed (for animation); Update says *what it is now*.
 */
export interface Update {
  gameId: string;
  seq: number /* int */;
  state?: State;
  seats: SeatInfo[];
  actions: Action[];
  waitingOn: string[];
  deadline?: number /* int64 */;
}
export interface ChatMessage {
  gameId: string;
  playerId: string;
  name: string;
  text: string;
  at: number /* int64 */;
}
/**
 * Kicked tells a user the host removed them from a game. Mid-game their
 * seat carries on under a bot.
 */
export interface Kicked {
  gameId: string;
  playerId: string;
}
export interface Ack {
  seq: number /* int */;
}
export interface Error {
  code: string;
  message: string;
}
